### ISSUE TITLE
Build pyinstaller

### ISSUE THREAD

**Issue by zhepoch** [pyocd/pyOCD#1004]

**Comment by flit** [comment]
Take a look at my [feature/binary_build](https://github.com/flit/pyOCD/tree/feature/binary_build) branch. There is a `scripts/pyocd.spec` file and `scripts/build_pyinstaller.sh`.  Unfortunately, it doesn't work yet due to an issue with the prettytable dependency. It builds ok, but when you run pyocd a `pkg_resources.DistributionNotFound` exception is raised when prettytable tries to call `pkg_resources.get_distribution()`. There is an attempt at a hook under `scripts/hooks` based on pyinstaller/pyinstaller#4809, but it doesn't work.

If you can make progress, that would by great! You can either comment here with your improvements or create a PR to my feature/binary_build branch.

Note that another option I haven't yet explored but seems promising is PyOxidizer.

**Comment by Littermonkey** [comment]
I found the root cause that package (Prettytable) __init__.py is an issue. and  I just added some code in that file by follow up :
`
from pkg_resources import get_distribution, DistributionNotFound
import os.path

try:
    _dist = get_distribution('prettytable')
    # Normalize case for Windows systems
    dist_loc = os.path.normcase(_dist.location)
    here = os.path.normcase(__file__)
    if not here.startswith(os.path.join(dist_loc, 'prettytable')):
        # not installed, but there is another version that *is*
        raise DistributionNotFound
except DistributionNotFound:
    __version__ = 'Please install this project with setup.py'
else:
    __version__ = _dist.version
`
it can work,  but when I execute './pyocd list --target' expose some warnning: 
`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIacUmZi/pyocd/debug/svd/svd_data.zip'
0000288:WARNING:loader:unable to open builtin SVD file: [Errno 2] No such file or directory: '/tmp/_MEIacUmZi/pyocd/debug/svd/svd_data.zip'
Traceback (most recent call last):
  File "pyocd/debug/svd/loader.py", line 37, in from_builtin
  File "pkg_resources/__init__.py", line 1135, in resource_stream
  File "pkg_resources/__init__.py", line 1383, in get_resource_stream
  File "pkg_resources/__init__.py", line 1386, in get_resource_string
  File "pkg_resources/__init__.py", line 1553, in _get
  File "/home/glb/build_pyocd/env/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 341, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIacUmZi/pyocd/debug/svd/svd_data.zip'
0000288:WARNING:loader:unable to open builtin SVD file: [Errno 2] No such file or directory: '/tmp/_MEIacUmZi/pyocd/debug/svd/svd_data.zip'
Traceback (most recent call last):
  File "pyocd/debug/svd/loader.py", line 37, in from_builtin
  File "pkg_resources/__init__.py", line 1135, in resource_stream
  File "pkg_resources/__init__.py", line 1383, in get_resource_stream
  File "pkg_resources/__init__.py", line 1386, in get_resource_string
  File "pkg_resources/__init__.py", line 1553, in _get
  File "/home/glb/build_pyocd/env/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 341, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIacUmZi/pyocd/debug/svd/svd_data.zip'
  Name                      Vendor                  Part Number                  Families   Source   
-----------------------------------------------------------------------------------------------------
  cc3220sf                  Texas Instruments       CC3220SF                                builtin  
  cortex_m                  Generic                 CoreSightTarget                         builtin  
  cy8c64_sysap              Cypress                 cy8c64_sysap                            builtin  
  cy8c64x5_cm0              Cypress                 cy8c64x5_cm0                            builtin  
  cy8c64x5_cm0_full_flash   Cypress                 cy8c64x5_cm0_full_flash                 builtin  
  cy8c64x5_cm4              Cypress                 cy8c64x5_cm4                            builtin  
  cy8c64x5_cm4_full_flash   Cypress                 cy8c64x5_cm4_full_flash                 builtin  
  cy8c64xa_cm0              Cypress                 cy8c64xA_cm0                            builtin  
  cy8c64xa_cm0_full_flash   Cypress                 cy8c64xA_cm0_full_flash                 builtin  
  cy8c64xa_cm4              Cypress                 cy8c64xA_cm4                            builtin  
  cy8c64xa_cm4_full_flash   Cypress                 cy8c64xA_cm4_full_flash                 builtin  
  cy8c64xx_cm0              Cypress                 cy8c64xx_cm0                            builtin  
  cy8c64xx_cm0_full_flash   Cypress                 cy8c64xx_cm0_full_flash                 builtin  
  cy8c64xx_cm0_nosmif       Cypress                 cy8c64xx_cm0_nosmif                     builtin  
  cy8c64xx_cm0_s25hx512t    Cypress                 cy8c64xx_cm0_s25hx512t                  builtin  
  cy8c64xx_cm4              Cypress                 cy8c64xx_cm4                            builtin  
  cy8c64xx_cm4_full_flash   Cypress                 cy8c64xx_cm4_full_flash                 builtin  
  cy8c64xx_cm4_nosmif       Cypress                 cy8c64xx_cm4_nosmif                     builtin  
  cy8c64xx_cm4_s25hx512t    Cypress                 cy8c64xx_cm4_s25hx512t                  builtin  
  cy8c6xx5                  Cypress                 CY8C6xx5                                builtin  
  cy8c6xx7                  Cypress                 CY8C6xx7                                builtin  
  cy8c6xx7_nosmif           Cypress                 CY8C6xx7_nosmif                         builtin  
  cy8c6xx7_s25fs512s        Cypress                 CY8C6xx7_S25FS512S                      builtin  
  cy8c6xxa                  Cypress                 CY8C6xxA                                builtin  
  hc32f003                  HDSC                    HC32F003                                builtin  
  hc32f005                  HDSC                    HC32F005                                builtin  
  hc32f030                  HDSC                    HC32F030                                builtin  
  hc32f072                  HDSC                    HC32F072                                builtin  
  hc32f120x6                HDSC                    HC32F120x6TA                            builtin  
  hc32f120x8                HDSC                    HC32F120x8TA                            builtin  
  hc32f190                  HDSC                    HC32F190                                builtin  
  hc32f196                  HDSC                    HC32F196                                builtin  
  hc32f46x                  HDSC                    HC32F46x                                builtin  
  hc32f4a0xg                HDSC                    HC32F4A0xG                              builtin  
  hc32f4a0xi                HDSC                    HC32F4A0xI                              builtin  
  hc32l072                  HDSC                    HC32L072                                builtin  
  hc32l073                  HDSC                    HC32L073                                builtin  
  hc32l110                  HDSC                    HC32L110                                builtin  
  hc32l130                  HDSC                    HC32L130                                builtin  
  hc32l136                  HDSC                    HC32L136                                builtin  
  hc32l190                  HDSC                    HC32L190                                builtin  
  hc32l196                  HDSC                    HC32L196                                builtin  
  hc32m120                  HDSC                    HC32M120                                builtin  
  hc32m423                  HDSC                    HC32M423                                builtin  
  k20d50m                   NXP                     K20D50M                                 builtin  
  k22f                      NXP                     K22F                                    builtin  
  k22fa12                   NXP                     K22FA12                                 builtin  
  k28f15                    NXP                     K28F15                                  builtin  
  k32l2b3                   NXP                     K32L2B3                                 builtin  
  k32w042s                  NXP                     K32W042S                                builtin  
  k64f                      NXP                     K64F                                    builtin  
  k66f18                    NXP                     K66F18                                  builtin  
  k82f25615                 NXP                     K82F25615                               builtin  
  ke15z7                    NXP                     KE15Z7                                  builtin  
  ke18f16                   NXP                     KE18F16                                 builtin  
  kinetis                   NXP                     Kinetis                                 builtin  
  kl02z                     NXP                     KL02Z                                   builtin  
  kl05z                     NXP                     KL05Z                                   builtin  
  kl25z                     NXP                     KL25Z                                   builtin  
  kl26z                     NXP                     KL26Z                                   builtin  
  kl27z4                    NXP                     KL27Z4                                  builtin  
  kl28z                     NXP                     KL28x                                   builtin  
  kl43z4                    NXP                     KL43Z4                                  builtin  
  kl46z                     NXP                     KL46Z                                   builtin  
  kl82z7                    NXP                     KL82Z7                                  builtin  
  kv10z7                    NXP                     KV10Z7                                  builtin  
  kv11z7                    NXP                     KV11Z7                                  builtin  
  kw01z4                    NXP                     KW01Z4                                  builtin  
  kw24d5                    NXP                     KW24D5                                  builtin  
  kw36z4                    NXP                     KW36Z4                                  builtin  
  kw40z4                    NXP                     KW40Z4                                  builtin  
  kw41z4                    NXP                     KW41Z4                                  builtin  
  lpc11u24                  NXP                     LPC11U24                                builtin  
  lpc11xx_32                NXP                     LPC11XX_32                              builtin  
  lpc1768                   NXP                     LPC1768                                 builtin  
  lpc4088                   NXP                     LPC4088                                 builtin  
  lpc4088dm                 NXP                     LPC4088dm                               builtin  
  lpc4088qsb                NXP                     LPC4088qsb                              builtin  
  lpc4330                   NXP                     LPC4330                                 builtin  
  lpc54114                  NXP                     LPC54114                                builtin  
  lpc54608                  NXP                     LPC54608                                builtin  
  lpc55s28                  NXP                     LPC55S28                                builtin  
  lpc55s69                  NXP                     LPC55S69                                builtin  
  lpc800                    NXP                     LPC800                                  builtin  
  lpc824                    NXP                     LPC824                                  builtin  
  m252kg6ae                 Nuvoton                 M252KG6AE                               builtin  
  m263kiaae                 Nuvoton                 M263KIAAE                               builtin  
  m487jidae                 Nuvoton                 M487JIDAE                               builtin  
  max32600                  Maxim                   MAX32600                                builtin  
  max32620                  Maxim                   MAX32620                                builtin  
  max32625                  Maxim                   MAX32625                                builtin  
  max32630                  Maxim                   MAX32630                                builtin  
  mimxrt1010                NXP                     MIMXRT1011xxxxx                         builtin  
  mimxrt1015                NXP                     MIMXRT1015xxxxx                         builtin  
  mimxrt1020                NXP                     MIMXRT1021xxxxx                         builtin  
  mimxrt1024                NXP                     MIMXRT1024xxxxx                         builtin  
  mimxrt1050                NXP                     MIMXRT1052xxxxB_hyperflash              builtin  
  mimxrt1050_hyperflash     NXP                     MIMXRT1052xxxxB_hyperflash              builtin  
  mimxrt1050_quadspi        NXP                     MIMXRT1052xxxxB_quadspi                 builtin  
  mimxrt1060                NXP                     MIMXRT1062xxxxA                         builtin  
  mimxrt1064                NXP                     MIMXRT1064xxxxA                         builtin  
  mps3_an522                Arm                     AN522                                   builtin  
  mps3_an540                Arm                     AN540                                   builtin  
  musca_a1                  Arm                     MuscaA1                                 builtin  
  musca_b1                  Arm                     MuscaB1                                 builtin  
  musca_s1                  Arm                     MuscaS1                                 builtin  
  ncs36510                  ONSemiconductor         NCS36510                                builtin  
  nrf51                     Nordic Semiconductor    NRF51                                   builtin  
  nrf52                     Nordic Semiconductor    NRF52832                                builtin  
  nrf52840                  Nordic Semiconductor    NRF52840                                builtin  
  rtl8195am                 Realtek Semiconductor   RTL8195AM                               builtin  
  s5js100                   Samsung                 S5JS100                                 builtin  
  stm32f051                 STMicroelectronics      STM32F051                               builtin  
  stm32f103rc               STMicroelectronics      STM32F103RC                             builtin  
  stm32f412xe               STMicroelectronics      STM32F412xE                             builtin  
  stm32f412xg               STMicroelectronics      STM32F412xG                             builtin  
  stm32f429xg               STMicroelectronics      STM32F429xG                             builtin  
  stm32f429xi               STMicroelectronics      STM32F429xI                             builtin  
  stm32f439xg               STMicroelectronics      STM32F439xG                             builtin  
  stm32f439xi               STMicroelectronics      STM32F439xI                             builtin  
  stm32f767zi               STMicroelectronics      STM32F767xx                             builtin  
  stm32l031x6               STMicroelectronics      STM32L031x6                             builtin  
  stm32l475xc               STMicroelectronics      STM32L475xC                             builtin  
  stm32l475xe               STMicroelectronics      STM32L475xE                             builtin  
  stm32l475xg               STMicroelectronics      STM32L475xG                             builtin  
  w7500                     WIZnet                  W7500                                   builtin  

`

**Comment by Littermonkey** [comment]
I found the root cause that package (Prettytable) __init__.py is an issue. and I just added some codes in that file like this :
`from pkg_resources import get_distribution, DistributionNotFound
import os.path
try:
_dist = get_distribution('prettytable')
dist_loc = os.path.normcase(_dist.location)
here = os.path.normcase(file)
if not here.startswith(os.path.join(dist_loc, 'prettytable')):
raise DistributionNotFound
except DistributionNotFound:
version = 'Please install this project with setup.py'
else:
version = _dist.version
`

**Comment by Littermonkey** [comment]
Despair is that when I execute "./pyocd list --target"  explore some warnnings, so I'm not sure if it's still a build binary issue. 
`./dist/pyocd list --target
0000215:WARNING:loader:unable to open builtin SVD file: [Errno 2] No such file or directory: '/tmp/_MEIp1l1zs/pyocd/debug/svd/svd_data.zip'
Traceback (most recent call last):
  File "pyocd/debug/svd/loader.py", line 37, in from_builtin
    zip_stream = pkg_resources.resource_stream("pyocd", BUILTIN_SVD_DATA_PATH)
  File "pkg_resources/__init__.py", line 1135, in resource_stream
  File "pkg_resources/__init__.py", line 1383, in get_resource_stream
  File "pkg_resources/__init__.py", line 1386, in get_resource_string
  File "pkg_resources/__init__.py", line 1553, in _get
  File "/home/glb/build_pyocd/env/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 341, in get_data
    with open(path, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIp1l1zs/pyocd/debug/svd/svd_data.zip'
`

**Comment by TeoMahnic** [comment]
Hi all,
as of our most recent releases, prebuilt binary distributions are now included in the release assets, so this issue is considered resolved. Please feel free to reopen or open a new issue if you run into any problems with the binaries.
