### ISSUE TITLE
target_kinetis.py AttributeError: 'AccessPort' object has no attribute 'read32'

### ISSUE THREAD

**Issue by Hoohaha** [pyocd/pyOCD#1015]
Hi @flit ,

I met a strange problem on kl28z target. 
Sometimes there occur exception in `target\family\target_kinetis.py`: 
**`AttributeError: 'AccessPort' object has no attribute 'read32'`**,
I know it is hardware issue, but how to make it do not display AttributeError.

Thanks. 

Full logs:

```
0000250:WARNING:common:STLink and CMSIS-DAPv2 probes are not supported because no libusb library was found.
0000250:INFO:board:Target type is kl28z
0000254:INFO:coresight_target:Asserting reset prior to connect
0000269:INFO:dap:DP IDR = 0x2ba01477 (v1 rev2)
0005276:INFO:ap:AP#0 IDR = 0x02000000 (AP var0 rev0)
0005276:INFO:ap:AP#1 IDR = 0x02000000 (AP var0 rev0)
0005276:INFO:ap:AP#2 IDR = 0x02000000 (AP var0 rev0)
0005276:ERROR:target_kinetis:KL28x: bad MDM-AP IDR (is 0x02000000)
0015286:CRITICAL:__main__:uncaught exception: 'AccessPort' object has no attribute 'read32'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pyocd\__main__.py", line 398, in run
    self._COMMANDS[self._args.cmd](self)
  File "C:\Python27\lib\site-packages\pyocd\__main__.py", line 742, in do_gdbserver
    with session:
  File "C:\Python27\lib\site-packages\pyocd\core\session.py", line 343, in __enter__
    self.open()
  File "C:\Python27\lib\site-packages\pyocd\core\session.py", line 461, in open
    self._board.init()
  File "C:\Python27\lib\site-packages\pyocd\board\board.py", line 85, in init
    self.target.init()
  File "C:\Python27\lib\site-packages\pyocd\core\soc_target.py", line 120, in init
    seq.invoke()
  File "C:\Python27\lib\site-packages\pyocd\utility\sequencer.py", line 213, in invoke
    resultSequence.invoke()
  File "C:\Python27\lib\site-packages\pyocd\utility\sequencer.py", line 208, in invoke
    resultSequence = call()
  File "C:\Python27\lib\site-packages\pyocd\target\family\target_kinetis.py", line 121, in check_flash_security
    self.aps[0].read32(CortexM.DHCSR)
AttributeError: 'AccessPort' object has no attribute 'read32'
```

**Comment by flit** [comment]
Hi @Hoohaha. This is a strange error! For some reason I don't recall seeing anything like this when I was working on the KL28 after we got the silicon back. 

Some questions for you:
- Is it intermittent?
- Is the same value always returned?
- Does it only happen when using the under-reset connect mode?
- Could it be related to power state, like the target is sleeping? (Some devices from other vendors sometimes have a similar behaviour where they return weird values in certain power states.)
- Is there a known way to recover?

Anything else you know about the issue would be helpful. (We can chat by email if you want.)
