### ISSUE TITLE
Exception in thread load-svd when flash app.bin to target.

### ISSUE THREAD

**Issue by xjtuecho** [pyocd/pyOCD#1181]
Target: GD32F150C6T6
PACKS: GigaDevice.GD32F1x0_DFP.3.1.1.pack
Command：`$ pyocd flash app.bin --target gd32f130c8 --pack="$PACKS/GigaDevice.GD32F1x0_DFP.3.1.1.pack"`

```
Flash Device...
Exception in thread load-svd:
Traceback (most recent call last):
  File "d:\dev\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "d:\dev\python36\lib\site-packages\pyocd\debug\svd\loader.py", line 71, in run
    self._svd_location.load()
  File "d:\dev\python36\lib\site-packages\pyocd\debug\svd\loader.py", line 47, in load
    self.device = SVDParser.for_xml_file(self.filename).get_device()
  File "d:\dev\python36\lib\site-packages\pyocd\debug\svd\parser.py", line 74, in for_xml_file
    return cls(ET.parse(path), remove_reserved)
  File "d:\dev\python36\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "d:\dev\python36\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: XML or text declaration not at start of entity: line 1, column 2

[---|---|---|---|---|---|---|---|---|----]
[========================================]
0001780:INFO:loader:Erased 0 bytes (0 sectors), programmed 0 bytes (0 pages), skipped 14336 bytes (14 pages) at 29.10 kB/s
```

**Comment by HoganPen** [comment]
GigaDevice manufacturers are required to configure the SVD files for relevant chips in the pyocd library. You can find the already adapted pyocd in the file "svd_data.zip" located at "d:\dev\python36\lib\site-packages\pyocd\debug\svd". A temporary solution is to capture exceptions, print logs, or output the results

<img width="708" height="227" alt="Image" src="https://github.com/user-attachments/assets/b2d8e9e8-ea0c-4f87-9724-ad0dbe7de4f2" />
