### ISSUE TITLE
pyocd command line cannot recognize path correctly when it contains "@"

### ISSUE THREAD

**Issue by Hoohaha** [pyocd/pyOCD#1424]
If command line options contains @ , the pyocd won't work as expected.

```bash
pyocd flash -W --format bin -u 02260000070b178700000000000000000000000097969905 -t mimxrt1015 "C:/xxxx/test@wifi/binaries/wifi_1015.bin"

0001275 C invalid literal for int() with base 0: 'wifi/binaries/evkmimxrt1015.bin' [__main__]
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\pyocd\__main__.py", line 161, in run
    status = cmd.invoke()
  File "C:\Program Files\Python39\lib\site-packages\pyocd\subcommands\load_cmd.py", line 104, in invoke
    base_address = int_base_0(suffix)
  File "C:\Program Files\Python39\lib\site-packages\pyocd\utility\cmdline.py", line 237, in int_base_0
    return int(x, base=0)
ValueError: invalid literal for int() with base 0: 'wifi/binaries/wifi_1015.bin'
```

**Comment by flit** [comment]
Hi @Hoohaha 😄 

That's because the flash/load command accepts a "@<address>" suffix on filenames to allow setting the load address for binary files without relying on the `--address` argument (since that won't work when loading multiple binary files). I'll have to change it to check if there's an existing file with the full argument value before attempting to process the `@` suffix.

Thanks for reporting this.
