### ISSUE TITLE
Issues with Renesas RA2A1

### ISSUE THREAD

**Issue by mtk11** [pyocd/pyOCD#1446]
Trying to use pyOCD with Renesas RA2A1, but getting the following error:

```
0001569 W Overlapping memory regions in file /root/.local/share/cmsis-pack-manager/Renesas/RA_DFP/4.0.0.pack (R7FA6M4AF3CFB_dual); deleting outer region. Further warnings will be suppressed for this file. [cmsis_pack]
0001606 C Target type r7fa2a1ab3cfj not recognized. Use 'pyocd list --targets' to see currently available target types. See <https://github.com/pyocd/pyOCD/blob/master/docs/target_support.md> for how to install additional target support. [__main__]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyocd/board/board.py", line 100, in __init__
    self.target = TARGET[self._target_type](session)
  File "/usr/local/lib/python3.9/dist-packages/pyocd/target/pack/pack_target.py", line 116, in _pack_target__init__
    super(self.__class__, self).__init__(session, self._pack_device.memory_map)
  File "/usr/local/lib/python3.9/dist-packages/pyocd/target/pack/cmsis_pack.py", line 681, in memory_map
    self._build_flash_regions()
  File "/usr/local/lib/python3.9/dist-packages/pyocd/target/pack/cmsis_pack.py", line 510, in _build_flash_regions
    packAlgo = self._load_flash_algo(algo_element.attrib['name'])
  File "/usr/local/lib/python3.9/dist-packages/pyocd/target/pack/cmsis_pack.py", line 644, in _load_flash_algo
    algo_data = self.pack.get_file(filename)
  File "/usr/local/lib/python3.9/dist-packages/pyocd/target/pack/cmsis_pack.py", line 131, in get_file
    return io.BytesIO(self._pack_file.read(filename))
  File "/usr/lib/python3.9/zipfile.py", line 1463, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.9/zipfile.py", line 1502, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python3.9/zipfile.py", line 1429, in getinfo
    raise KeyError(
KeyError: "There is no item named 'Flash/RA2A1_256K.FLM' in the archive"
```

**Comment by flit** [comment]
Thanks to @imi415, there is a fix (#1461) for this issue that will appear in the next release. The problem is that the Renesas RA series CMSIS-Pack uses a non-standard layout (but one which is supported in Arm MDK).
